import Foundation

// MARK: - AgentRecommendation
//
// A proactive, personalized agent task Mira suggests to the user (HeyClicky-parity
// "proactive agents"). Generated by RecommendationEngine from local signals
// (app-usage digest, memory, connected integrations, recent projects) and shown
// as an Approve/Dismiss card. Approve → AgentJobStore.submitJob (the normal Agents
// lane). See docs/specs/heyclicky-parity-proactive-and-skills.md (Gap A).

struct AgentRecommendation: Identifiable, Codable, Equatable {
    enum Status: String, Codable { case pending, approved, dismissed }

    let id: UUID
    let title: String            // short imperative label
    let rationale: String        // 1 sentence: why this, for THIS user
    let taskPrompt: String       // self-contained instruction handed to the agent on approve
    let isWebsiteBuild: Bool      // route through the Website Builder (Pro) lane when true
    let confidence: Double
    let generatedAt: Date
    var status: Status

    init(id: UUID = UUID(), title: String, rationale: String, taskPrompt: String,
         isWebsiteBuild: Bool, confidence: Double, generatedAt: Date = Date(),
         status: Status = .pending) {
        self.id = id
        self.title = title
        self.rationale = rationale
        self.taskPrompt = taskPrompt
        self.isWebsiteBuild = isWebsiteBuild
        self.confidence = confidence
        self.generatedAt = generatedAt
        self.status = status
    }
}

// MARK: - RecommendationStore

@MainActor
final class RecommendationStore: ObservableObject {
    static let shared = RecommendationStore()

    /// Recommendations still worth showing (pending and < 24h old).
    @Published private(set) var pending: [AgentRecommendation] = []

    private var all: [AgentRecommendation] = []
    private let staleAfter: TimeInterval = 24 * 60 * 60

    private let fileURL: URL = {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = support.appendingPathComponent("Mira", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("recommendations.json")
    }()

    private init() {
        load()
        refresh()
    }

    /// Replace the current pending set with a freshly generated batch (a new
    /// digest supersedes the last). Approved/dismissed history is preserved.
    func replacePending(with recs: [AgentRecommendation]) {
        all.removeAll { $0.status == .pending }
        all.append(contentsOf: recs)
        persist()
    }

    func markApproved(_ id: UUID) { setStatus(id, .approved) }
    func markDismissed(_ id: UUID) { setStatus(id, .dismissed) }

    private func setStatus(_ id: UUID, _ status: AgentRecommendation.Status) {
        guard let i = all.firstIndex(where: { $0.id == id }) else { return }
        all[i].status = status
        persist()
    }

    private func refresh() {
        let cutoff = Date().addingTimeInterval(-staleAfter)
        pending = all
            .filter { $0.status == .pending && $0.generatedAt > cutoff }
            .sorted { $0.confidence > $1.confidence }
    }

    private func persist() {
        refresh()
        if let data = try? JSONEncoder().encode(all) { try? data.write(to: fileURL) }
    }

    private func load() {
        guard let data = try? Data(contentsOf: fileURL),
              let decoded = try? JSONDecoder().decode([AgentRecommendation].self, from: data) else { return }
        all = decoded
    }
}
