#!/usr/bin/env python3
"""
Generate diagrams from Mermaid or Excalidraw JSON notation.

Outputs a self-contained HTML file the user can open in any browser.
No external Python deps — stdlib only.

Args JSON (stdin):
  {
    format: "mermaid" | "excalidraw",   (default: mermaid)
    definition: "<mermaid code or excalidraw JSON string>",
    title?: "<diagram title>",
    path?: "<abs_path>.html",           (default: ~/Desktop/<title>.html)
    theme?: "dark" | "light"            (default: dark)
  }

Mermaid example:
  {format:"mermaid", title:"Auth Flow",
   definition:"flowchart TD\\n  A[User] --> B[Login]\\n  B --> C{Valid?}\\n  C -->|Yes| D[Dashboard]\\n  C -->|No| E[Error]"}

Excalidraw example:
  {format:"excalidraw", title:"Architecture",
   definition:"{\"type\":\"excalidraw\",\"version\":2,\"elements\":[...]}"}

Output JSON:
  {success, path, format, title, error?}
"""
import sys, json, os, re

def out(data: dict):
    print(json.dumps(data))

DARK_BG  = "#1a1a1f"
LIGHT_BG = "#ffffff"

# ── Mermaid HTML ──────────────────────────────────────────────────────────────

MERMAID_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: {bg};
    color: {fg};
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 32px 20px;
  }}
  h1 {{
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 24px;
    opacity: 0.85;
    letter-spacing: -0.3px;
  }}
  #diagram {{
    background: {card_bg};
    border-radius: 12px;
    padding: 28px 32px;
    box-shadow: 0 2px 20px rgba(0,0,0,0.35);
    max-width: 100%;
    overflow: auto;
  }}
  .mermaid {{ display: flex; justify-content: center; }}
  footer {{
    margin-top: 24px;
    font-size: 11px;
    opacity: 0.3;
  }}
</style>
</head>
<body>
{title_tag}
<div id="diagram">
  <div class="mermaid">
{definition}
  </div>
</div>
<footer>Generated by Mira · Mermaid 10</footer>
<script>
  mermaid.initialize({{
    startOnLoad: true,
    theme: '{mermaid_theme}',
    securityLevel: 'loose',
    fontFamily: '-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif',
  }});
</script>
</body>
</html>"""

# ── Excalidraw HTML ───────────────────────────────────────────────────────────

EXCALIDRAW_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: {bg};
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    height: 100vh;
    display: flex;
    flex-direction: column;
  }}
  h1 {{
    padding: 12px 20px;
    font-size: 15px;
    font-weight: 600;
    color: {fg};
    opacity: 0.80;
    flex-shrink: 0;
  }}
  #root {{ flex: 1; }}
</style>
</head>
<body>
{title_tag}
<div id="root"></div>
<script type="module">
  import {{ Excalidraw }} from "https://esm.run/@excalidraw/excalidraw";
  import {{ createElement }} from "https://esm.run/react@18";
  import {{ createRoot }} from "https://esm.run/react-dom@18/client";

  const data = {definition};
  const App = () => createElement(Excalidraw, {{
    initialData: {{
      elements: data.elements || [],
      appState: {{ ...(data.appState || {{}}), theme: '{excalidraw_theme}' }},
    }},
    theme: '{excalidraw_theme}',
  }});
  createRoot(document.getElementById("root")).render(createElement(App));
</script>
</body>
</html>"""

# ── build HTML ────────────────────────────────────────────────────────────────

def build_mermaid_html(definition: str, title: str, theme: str) -> str:
    dark    = theme == "dark"
    bg      = DARK_BG if dark else LIGHT_BG
    fg      = "#e8e8ef" if dark else "#1a1a1f"
    card_bg = "#22222a" if dark else "#f7f7fa"
    mermaid_theme = "dark" if dark else "default"
    title_tag = f"<h1>{title}</h1>" if title else ""
    return MERMAID_TEMPLATE.format(
        title=title or "Diagram",
        bg=bg, fg=fg, card_bg=card_bg,
        mermaid_theme=mermaid_theme,
        definition=definition,
        title_tag=title_tag,
    )

def build_excalidraw_html(definition: str, title: str, theme: str) -> str:
    dark = theme == "dark"
    bg   = DARK_BG if dark else LIGHT_BG
    fg   = "#e8e8ef" if dark else "#1a1a1f"
    ex_theme = "dark" if dark else "light"
    title_tag = f"<h1>{title}</h1>" if title else ""
    # Validate JSON
    try:
        json.loads(definition)
    except Exception as e:
        raise ValueError(f"Invalid Excalidraw JSON: {e}")
    return EXCALIDRAW_TEMPLATE.format(
        title=title or "Diagram",
        bg=bg, fg=fg,
        excalidraw_theme=ex_theme,
        definition=definition,
        title_tag=title_tag,
    )

# ── main ─────────────────────────────────────────────────────────────────────

def main():
    try:
        args = json.load(sys.stdin)
    except Exception:
        args = {}

    fmt        = args.get("format", "mermaid").lower()
    definition = args.get("definition", "").strip()
    title      = args.get("title", "Diagram").strip()
    theme      = args.get("theme", "dark").lower()
    path_arg   = args.get("path", "")

    if not definition:
        out({"success": False, "error": "definition is required"}); return

    # Resolve output path
    safe_name = re.sub(r'[^\w\- ]', '', title).strip().replace(' ', '_') or "diagram"
    if path_arg:
        path = os.path.expanduser(path_arg)
        if not path.lower().endswith(".html"):
            path += ".html"
    else:
        path = os.path.expanduser(f"~/Desktop/{safe_name}.html")

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)

    try:
        if fmt == "mermaid":
            html = build_mermaid_html(definition, title, theme)
        elif fmt in ("excalidraw", "excali"):
            html = build_excalidraw_html(definition, title, theme)
        else:
            out({"success": False, "error": f"Unknown format '{fmt}'. Use: mermaid, excalidraw"}); return

        with open(path, "w", encoding="utf-8") as f:
            f.write(html)

        out({"success": True, "path": path, "format": fmt, "title": title})

    except Exception as e:
        out({"success": False, "error": str(e)})

main()
